### ISSUE TITLE
Add mathematical formula rendering such as Katex

### ISSUE THREAD

**Issue by hprogq** [importantimport/urara#11]
Hey there!
I found that the program cannot render mathematical formulas in the process of using Urara, could you please help me to provide a solution?

写题解发现没法加数学公式，现在直接以rehype插件的形式加到mdsvex的配置中好像不会生效，可能是我对svelte还不够了解，应该怎么做呐
我之前看到的解决方案是可以在渲染静态文件的时候将其转为SVG格式的图片，这样能解决单页面应用需要主动重载渲染的问题，有好的解决方案吗？
感谢！

**Comment by kwaa** [comment]
I think you can follow this issue (pngwn/MDsveX#302) and try using [rehype-katex-svelte](https://github.com/kwshi/rehype-katex-svelte).

我認為你可以關注此 issue 並嘗試使用 rehype-katex-svelte。 （連接同上）

**Comment by hprogq** [comment]
Appreciate a lot!

好的，感谢！
