### ISSUE TITLE
404 pages not working as intented when deployed

### ISSUE THREAD

**Issue by kwchang0831** [importantimport/urara#14]
## Expected Behavior
In local dev, 404 pages are working as intented. 
For non-existent path, it will generate dynamic 404 pages like the following image.
![image](https://user-images.githubusercontent.com/88667293/166106010-9294ec47-5d99-483e-98b9-95e315b28db8.png)

## Current Behavior
However, when depolyed on both vercel and netlify, it will show function crash message.
On Vercel, it will always show function crash message.
On Netlify, for the same path it will show the crash message the first time. Next time, it will show the correct 404 page.

## To Reproduce on Vercel

Go to the following URL, it will show function crash message
https://kwaa.dev/404

Result:
![image](https://user-images.githubusercontent.com/88667293/166106385-6c2497f7-4aac-49f4-b8d9-096458ed5e9f.png)

Go to the instance on Vercel > `View Build Logs` > `Functions` > `Realtime Logs`
You will get similar erorr like the following image.
![image](https://user-images.githubusercontent.com/88667293/166106365-62852c2a-75ff-4c86-b81a-3a4827f5af8f.png)

## To Reporduce on Netlify

Go to the following URL, the 1st time it will show function crash message
https://urara-demo.netlify.app/404

Result:
![image](https://user-images.githubusercontent.com/88667293/166106442-89466ac6-dea7-48ba-a17a-832487464c6a.png)

Go to the following URL, the 2nd time it will show the correct 404 page
https://urara-demo.netlify.app/404

Result:
![image](https://user-images.githubusercontent.com/88667293/166106495-1ef4a63a-4ac8-4071-b1cc-da7c6a4d4b67.png)

**Comment by kwaa** [comment]
This seems to have started after one of the updates and I'm not sure how to fix it at the moment;
I'll try to fix it later.

**Comment by kwaa** [comment]
Update: what is certain at the moment is that it will report an error even if there is only plain text.

**Comment by kwaa** [comment]
Update: It works fine after removing the `html-minifier` import. possible dependency issue

**Comment by kwaa** [comment]
I think this issue is the same as sveltejs/kit#4247.
as a workaround, I'm considering to stop using `html-minifier` and wait for a better solution.
