### ISSUE TITLE
Metadata not provided as expected

### ISSUE THREAD

**Issue by Myrmod** [importantimport/urara#21]
Hello,

I just cloned the repository and started it. Somehow though I am not able to provide a meta description to any of my posts using something like the following at the top of the `post.svelte.md` file.

```
---
title: 'My title'
summary: 'My summary'
date: 2022-06-11
lastmod: 2022-06-11
tags:
  - 'tag1'
  - 'tag2'
cover: '/post/cover.jpg'
---
```

For example using this:
```js
// src/lib/components/head_opengraph.svelte
console.log(post)
```

I get an almost empty `post` object.

I will try to debug this further and provide a cleaned example if I can.

best regards!

**Comment by kwaa** [comment]
Hello, [urara-demo](https://urara-demo.netlify.app) and [my blog](https://kwaa.dev) seem to provide metadata properly. have you made any changes to the code?

![image](https://user-images.githubusercontent.com/50108258/173185666-c3d4b040-791b-4bc7-ace7-1fbacf9921b8.png)

**Comment by Myrmod** [comment]
I just uploaded it: https://github.com/Myrmod/sveltekit-blog-mdx

**Comment by Myrmod** [comment]
I must have changed something. I guess I will compare it to the original. :/

**Comment by kwaa** [comment]
> I just uploaded it: https://github.com/Myrmod/sveltekit-blog-mdx

🤔 Well, obviously your `summary` needs to be in double quotes.

```diff
title: 'NPM packages are dangerous'
- summary: 'Often we don't want to write parts of our applications ourselves. So we just import them through a package manager like npm. However, this can post serious security risks.'
+ summary: "Often we don't want to write parts of our applications ourselves. So we just import them through a package manager like npm. However, this can post serious security risks."
date: 2022-06-11
lastmod: 2022-06-11
tags:
  - 'NPM packages are dangerous'
  - 'npm'
  - 'vitejs'
cover: '/npm-packages-are-dangerous/cover.jpg'
```

Please also refer to the latest FrontMatter format, as the sample article has not been updated for a long time: [global.d.ts](https://github.com/importantimport/urara/blob/main/src/global.d.ts)

```diff
title: 'NPM packages are dangerous'
summary: "Often we don't want to write parts of our applications ourselves. So we just import them through a package manager like npm. However, this can post serious security risks."
- date: 2022-06-11
- lastmod: 2022-06-11
+ created: 2022-06-11
+ updated: 2022-06-11
tags:
  - 'NPM packages are dangerous'
  - 'npm'
  - 'vitejs'
- cover: '/npm-packages-are-dangerous/cover.jpg'
+ photo: '/npm-packages-are-dangerous/cover.jpg'
```

**Comment by Myrmod** [comment]
You're right about the double quotes. But why is that?

**Comment by kwaa** [comment]
> You're right about the double quotes. But why is that? Why does it work with the title?

Because you already have a single quote in your summary, it will conflict with the single quote used to mark the paragraph.

**Comment by Myrmod** [comment]
Oh god, sorry for the dumb question. I didn't see. ^^'
