### ISSUE TITLE
RSS feed is invalid

### ISSUE THREAD

**Issue by jcayzac** [importantimport/urara#3]
<img width="497" alt="Screen Shot 2021-12-31 at 15 54 30" src="https://user-images.githubusercontent.com/106682/147808467-b67001ea-e4ac-4f70-967c-b3cfe9b073f3.png">

**Comment by jcayzac** [comment]
It looks like `&` isn't escaped.

**Comment by kwaa** [comment]
Thanks for the feedback! this issue should have been fixed.
