### ISSUE TITLE
How do you add a new post ?

### ISSUE THREAD

**Issue by regnou** [importantimport/urara#35]
Hi,
Please could you explain how I am supposed to add a new post ? 
Tks

**Comment by kwaa** [comment]
Create new folders and files in the `urara` folder.

- `urara/my-new-post/+page.md => https://example.com/my-new-post`
- `urara/my-mdx-post/+page.svelte.md => https://example.com/my-mdx-post`
- `urara/my-new-post/my-new-new-post/+page.md => https://example.com/my-new-post/my-new-new-post`

and add the appropriate Frontmatter and content to it.
