### ISSUE TITLE
在 Safari 内核的浏览器上，在标题栏上固定的一些文章在访问时需要手动刷新

### ISSUE THREAD

**Issue by Interstellar750** [importantimport/urara#39]
在 `/src/lib/config/general.ts` 文件内第 124 行 `export const header: HeaderConfig {}` 内设定的 Header 内容，在 iOS 的 Safari 与 Chrome 浏览器都没法正常访问，需要手动刷新页面才能正常显示页面

但有一个奇怪的现象，如果点击了标题栏的按钮并手动刷新，这个时候再次点击标题栏内的其他文章又可以正常访问了

不过也不是所有标题栏的页面都无法在 iOS 直接点击访问，例如您博客的 [Friends](https://kwaa.dev/friends) 页面是可以像普通文章那样直接访问的

~~您的博客主页好多文章在 iOS 似乎都有问题~~

**Comment by Interstellar750** [comment]
好像在 Issue 里放不了配图，就在这里发了

![image](https://user-images.githubusercontent.com/38517305/200169735-78229659-98da-48c0-bdb1-75f275d97610.gif)

**Comment by kwaa** [comment]
> 在 `/src/lib/config/general.ts` 文件内第 124 行 `export const header: HeaderConfig {}` 内设定的 Header 内容，在 iOS 的 Safari 与 Chrome 浏览器都没法正常访问，需要手动刷新页面才能正常显示页面

能详细说明一下吗？我这边是正常的，也可能是因为我的自定义 Header 没有动态内容

> 但有一个奇怪的现象，如果点击了标题栏的按钮并手动刷新，这个时候再次点击标题栏内的其他文章又可以正常访问了
> 
> 不过也不是所有标题栏的页面都无法在 iOS 直接点击访问，例如您博客的 [Friends](https://kwaa.dev/friends) 页面是可以像普通文章那样直接访问的
> 
> ~您的博客主页好多文章在 iOS 似乎都有问题~

我通过 [BrowserStack](browserstack.com) (Safari on iPhone 14 Pro / 13 Pro) 对我的博客进行了测试，访问标题栏固定文章似乎没有问题。

**Comment by Interstellar750** [comment]
> 能详细说明一下吗？我这边是正常的，也可能是因为我的自定义 Header 没有动态内容

并不是 Header 的问题，这个问题是其他的原因

我测试了几次，在我自己的博客上，我发现加上了 tags 的页面即使被放到了标题栏上也不会有问题，或者说，其实是没有 tags 的文章就会导致这个问题

然后我使用了您的博客作为对照，但您固定在标题栏的文章中有些是带标签的，但都无法访问，在主页的文章也是部分有标签部分文章没有，找不到头绪了

> 我通过 [BrowserStack](https://browserstack.com) (Safari on iPhone 14 Pro / 13 Pro) 对我的博客进行了测试，访问标题栏固定文章似乎没有问题。

这个嘛，那就可能是我的 iOS 设备和 Safari 版本过低 （14.4.2），应该就是旧版特性了😰

**Comment by kwaa** [comment]
> 并不是 Header 的问题，这个问题是其他的原因

没有看懂，感觉信息不够

> 这个嘛，那就可能是我的 iOS 设备和 Safari 版本过低 （14.4.2），应该就是旧版特性了😰

看起来是了，BrowserStack 上 iOS 14 及以下会有这个问题；

由于这和浏览器版本相关，我没有办法也不会进行修复。

[Safari is the new Internet Explorer](https://www.safari-is-the-new-ie.com/)
