### ISSUE TITLE
Fix A11y Warning

### ISSUE THREAD

**Issue by kwaa** [importantimport/urara#42]
The old component did not do well in a11y and needs to be fixed.

**Comment by Louiskin59** [comment]
hello，i'm in trouble.
Here's the problem.
`Your Node version is incompatible with "/@sveltejs/kit/1.0.0-next.535_svelte@3.51.0+vite@3.2.4".`

`Expected version: >=16.14`
`Got: v14.19.2`

I tried to change my node version,but it doesn't work.
So I need your help.

Thx.
