### ISSUE TITLE
Fix the wrong style

### ISSUE THREAD

**Issue by kwaa** [importantimport/urara#44]
There were many style errors after the update that needed to be fixed.

**Comment by Interstellar750** [comment]
依然有一个样式问题没有修复，例如当您在 `src/lib/config/general.ts` 文件中添加

```
    {
      text: 'Urara',
      children: [
        {
          text: 'Re: Introducing Urara',
          link: '/intro-urara/re'
        },
        {
          text: 'Introducing Urara',
          link: '/intro-urara'
        },
        {
          text: 'Urara 的 ToC (文章目录) 实现',
          link: '/intro-urara/toc'
        }
      ]
    },
```

这种样式的折叠标题时，点击后的窗口会仅以矩形显示

![IMG_20221118_211054_922.jpg](https://user-images.githubusercontent.com/38517305/202713049-de94035d-d4ca-4f17-b856-aef003b0285b.jpg)
