### ISSUE TITLE
Login for utterances and giscus don't seem to work.

### ISSUE THREAD

**Issue by SarcevicAntonio** [importantimport/urara#47]
I tried using utterances and giscus for comments but Sign In with Github doesn't seem to work right. Also doesn't work on https://kwaa.dev/ for example.

I added the following post config
```
import type { PostConfig } from '$lib/types/post'

export const post: PostConfig = {
  comment: {
    use: ['Giscus'],
    giscus: {
      repo: 'SarcevicAntonio/SarcevicAntonio',
      repoID: 'MDEwOlJlcG9zaXRvcnkxODkzMDAxNjM=',
      category: 'Comments',
      categoryID: 'DIC_kwDOC0h9w84CSwfL',
      reactionsEnabled: true,
      inputPosition: 'top',
      lang: 'en',
      theme: 'preferred_color_scheme',
      loading: 'lazy'
    }
  }
}
```

Result: sign in button redirects to main page and user isn't signed in.

Expected: sign in button redirects back to post page and user can comment.

**Comment by kwaa** [comment]
Seems to be caused by some SvelteKit update, which worked before that; no changes in the comment-related code.

**Comment by kwaa** [comment]
I may need to rewrite the comment component, or use the svelte component of giscus...

**Comment by SarcevicAntonio** [comment]
[Today I tried using the @giscus/svelte component](https://github.com/SarcevicAntonio/SarcevicAntonio/commit/bf2e8270447a5a11a12f037215fe36bb10a1a46d) and it does the same on prod. In dev it works fine, but in prod (on vercel) it redirects weirdly and I'm not logged in. Seems like a SvelteKit isse then I guess 🤷

**Comment by SarcevicAntonio** [comment]
I got news! It seems to be an issue with the Service Worker provided by Vite Plugin PWA.

I disabled it using `selfDestroying: true,`, because it also made other links behave weirdly (like the sitemap and atom links in the demo app) and now the @giscus/svelte Component works as it should!

**Comment by kwaa** [comment]
Setting up the workbox glob in my blog seems to have solved this problem. https://github.com/kwaa/blog/commit/e90d2de50acbe4d58bc3c1ea71a66bda247ab39b

https://github.com/kwaa/blog/blob/e90d2de50acbe4d58bc3c1ea71a66bda247ab39b/vite.config.ts#L62-L65

I'll push the patch later. btw, would you like to have your blog listed in [README](https://github.com/importantimport/urara#-sites)?
