### ISSUE TITLE
help me,plz. orz

### ISSUE THREAD

**Issue by Louiskin59** [importantimport/urara#48]
hello，i'm in trouble.
Here's the problem.
`Your Node version is incompatible with "/@sveltejs/kit/1.0.0-next.535_svelte@3.51.0+vite@3.2.4".`

`Expected version: >=16.14`
`Got: v14.19.2`

I tried to change my node version,but it doesn't work.
So I need your help.

Thx.

**Comment by kwaa** [comment]
[How To Ask Questions The Smart Way
](http://www.catb.org/~esr/faqs/smart-questions.html)

When you ask you should provide as much information as possible, such as the operating system and how to install Node.js and so on.

**Comment by Sevichecc** [comment]
So what's your Node version now?

**Comment by Louiskin59** [comment]
I have changed node versions v18.12.1, v16.14.2 and v14.19.2, as shown above.
They all report the same error message.
Is it my operating system? I use Windows.

**Comment by kwaa** [comment]
I recommend uninstalling Node.js completely first, and try installing the latest 19.2.0 from the [official website](https://nodejs.org/).

**Comment by Louiskin59** [comment]
okay,I'll try.thx :)

**Comment by Louiskin59** [comment]
I solved the problem. 
It seems that there is a problem with my pnpm. 
After I delete the pnpm related files on the pnmp official website and reinstall the pnpm, I can install the dependency normally.
：）perfect
