### ISSUE TITLE
Back button doesn't seem to work to return to home page

### ISSUE THREAD

**Issue by satur9day** [importantimport/urara#52]
I noticed this after downloading an running my own version of the Urara locally. The demo site https://urara-demo.netlify.app/ also has this issue. https://kwaa.dev/ does not seem to have this issue so wondering what is causing it, seems like there probably is a fix for it though unsure of what it is.

If you navigate to any page from the homepage, for example from urara-demo.netlify.app to urara-demo.netlify.app/hello-world/ then press the back arrow, the URL will update to the home page but the page itself stays the same. Only refreshing the page or pressing the home button will bring you back to the home page. If you go between any other 2 pages that aren't the homepage, like for example site/page1 to site/page2 the back button works fine, so it is only the home page.

**Comment by kwaa** [comment]
I'm not quite sure what caused this.
Maybe you can try downgrading to the same `@sveltejs/kit` version as my blog (`1.0.0-next.544_svelte@3.51.0+vite@3.2.3`)
This issue will remain open until the urara-demo error is resolved.

**Comment by kwaa** [comment]
The browser navigates fine when I replace the home page with other content, I may need to refactor this section.

**Comment by alphacornutum** [comment]
I believe the issue is the `window.window.history.replaceState` on the home page. I replaced it with Sveltekit's `goto` function which fixes it for me.
I created a PR: https://github.com/importantimport/urara/pull/61
