### ISSUE TITLE
upgrade an old blog generated to the last urara

### ISSUE THREAD

**Issue by vincenzopalazzo** [importantimport/urara#54]
I was wondering if it is possible upgrade an old blog generated to the last version of urara.

**Comment by kwaa** [comment]
Of course you can.
The easiest way to do this is to generate a new repo from urara/main and move all your previous data.
A more complex, but continuously updatable method is to use something like [pull bot](https://github.com/wei/pull), which automatically sync with upstream.

**Comment by kwaa** [comment]
Also worth noting: there are no major changes that require manual adjustments starting with Edition Delta, but there may be later.
If using the pull bot solution, please note the migration guidelines that may appear in the discussion.

**Comment by vincenzopalazzo** [comment]
Thanks!
