### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by janosh** [importantimport/urara#6]
https://urara-docs.netlify.app is no longer reachable. Caught in [`awesome-svelte-kit` CI](https://github.com/janosh/awesome-svelte-kit/runs/5367836902?check_suite_focus=true#step:4:187).

**Comment by kwaa** [comment]
🤔 I think it's probably because I'm using `Array.prototype.at()` (It looks like neither Nerlify nor Vercel are compatible, or is my tsconfig setup wrong?)
anyway, this will be fixed in a few hours.
