### ISSUE TITLE
Markdown parser for latex based equations

### ISSUE THREAD

**Issue by sandeshkatakam** [importantimport/urara#64]
I am getting errors when I use latex equations in my markdown posts. Even for characters like this ' and \pi \gamma are not working..
It throws this error: Expecting Unicode escape sequence \uXXXX

Please help me resolve this error. I heavily rely on latex math equations for my blog posts. Please suggest a fix as soon as possible.

**Comment by kwaa** [comment]
Duplicates of https://github.com/importantimport/urara/issues/11
LaTeX is still not intended to be supported by default, so please refer to https://github.com/importantimport/urara/pull/65 to make changes to your own repo.
Related: https://github.com/pngwn/MDsveX/issues/302
