### ISSUE TITLE
Missing start script

### ISSUE THREAD

**Issue by hmmhmmhm** [importantimport/urara#71]
Currently, build command is specified, but the start command is not specified.
In some cloud environments, it is necessary to specify the execution command of the build copy through the start command.

I think it would be good to add the following like this command.
```json
{
  "start": "serve build"
}
```

**Comment by kwaa** [comment]
Can you say which cloud environments specifically?

Also, I don't quite understand this "serve build". Is it `dev` or `build`?

**Comment by hmmhmmhm** [comment]
@kwaa `railway.dev` and `heroku.com` required start command in script.
"serve build" is a project in vercel that serves html that exists in the ./build path. It can be used for production
https://github.com/vercel/serve

**Comment by kwaa** [comment]
Considering that Urara is primarily a static build, I wouldn't recommend that you host it at Railway or Heroku.
Nonetheless, I'll add this in the next update.
Maybe it's optional and only installed when you run it: `"start": "pnpm dlx -y serve build"`

**Comment by hmmhmmhm** [comment]
Good! I think people who want to raise it lightly will prefer it. (Of course, it's better to use s3, netlifly, or r2.)

**Comment by kwaa** [comment]
It seems like it would be better to build and run directly with `@sveltejs/adapter-node`.

I've been a little busy lately, so this may be delayed until two weeks from now.

You can make changes to your repository ahead of time:

```bash
pnpm add -D @sveltejs/adapter-node
```

```ts
svelte.config.ts
import adapterNode from '@sveltejs/adapter-node'

export default {
  ...
  kit: {
    adapter: adapterNode()
  }
}
```

```json
{
  "start": "pnpm build && node build"
}
```

**Comment by kwaa** [comment]
It should be resolved, let me know if there are any other issues.
