### ISSUE TITLE
Can't deploy

### ISSUE THREAD

**Issue by favnfavnfavn** [importantimport/urara#76]
8:23:33 PM: Installing npm packages using pnpm version 8.14.1
8:23:33 PM:  ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json
8:23:33 PM: Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
8:23:33 PM:     Failure reason:
8:23:33 PM:     specifiers in the lockfile ({"@builder.io/partytown":"^0.7.6","@unocss/extractor-svelte":"^0.53.6","sharp":"^0.30.7","@iconify-json/heroicons-outline":"^1.1.6","@iconify-json/heroicons-solid":"^1.1.7","@iconify-json/simple-icons":"^1.1.61","@sveltejs/adapter-node":"1.3.1","@sveltejs/adapter-static":"2.0.2","@sveltejs/adapter-vercel":"3.0.2","@sveltejs/kit":"^1.22.3","@tailwindcss/typography":"^0.5.9","@types/unist":"^2.0.7","@typescript-eslint/eslint-plugin":"^5.62.0","@typescript-eslint/parser":"^5.62.0","@vite-pwa/sveltekit":"^0.1.3","autoprefixer":"^10.4.14","chalk":"^5.3.0","chokidar":"^3.5.3","cross-env":"^7.0.3","cssnano":"^5.1.15","daisyui":"^2.52.0","eslint":"^8.45.0","eslint-config-prettier":"^8.8.0","eslint-plugin-svelte3":"^4.0.0","fenceparser":"^2.2.0","fff-flavored-frontmatter":"~0.4.2","github-slugger":"^2.0.0","mdast-util-to-string":"^3.2.0","mdsvex":"^0.11.0","npm-run-all":"^4.1.5","postcss":"^8.4.27","postcss-preset-env":"^7.8.3","prettier":"^2.8.8","prettier-plugin-svelte":"^2.10.1","rehype-autolink-headings":"^6.1.1","rehype-external-links":"^1.0.1","rehype-slug":"^5.1.0","remark":"^14.0.3","remark-fff":"~0.4.2","remark-footnotes":"~2.0.0","rollup-plugin-visualizer":"^5.9.2","shiki-twoslash":"^3.1.2","svelte":"4.1.1","svelte-bricks":"^0.1.7","svelte-check":"^3.4.6","svelte-preprocess":"^5.0.4","tailwindcss":"^3.3.3","tslib":"^2.6.0","typescript":"^5.1.6","unist-util-visit":"^5.0.0","unocss":"^0.53.6","vite":"^4.4.6","vite-plugin-pwa":"^0.16.4","workbox-window":"^7.0.0"}) don"t match specs in package.json ({"@iconify-json/heroicons-outline":"^1.1.4","@iconify-json/heroicons-solid":"^1.1.5","@sveltejs/adapter-auto":"next","@sveltejs/adapter-node":"next","@sveltejs/adapter-static":"next","@sveltejs/kit":"1.0.0-next.456","@tailwindcss/typography":"^0.5.4","@types/node":"^18.7.14","@types/unist":"^2.0.6","@typescript-eslint/eslint-plugin":"^5.36.1","@typescript-eslint/parser":"^5.36.1","autoprefixer":"^10.4.8","chalk":"^5.0.1","chokidar":"^3.5.3","cross-env":"^7.0.3","cssnano":"^5.1.13","daisyui":"^2.24.0","eslint":"^8.23.0","eslint-config-prettier":"^8.5.0","eslint-plugin-svelte3":"^4.0.0","fenceparser":"2.0.0","fff-flavored-frontmatter":"~0.2.2","github-slugger":"^1.4.0","mdast-util-to-string":"^3.1.0","mdsvex":"^0.10.6","npm-run-all":"^4.1.5","postcss":"^8.4.16","prettier":"^2.7.1","prettier-plugin-svelte":"^2.7.0","rehype-autolink-headings":"^6.1.1","rehype-external-links":"^1.0.1","rehype-slug":"^5.0.1","remark":"^14.0.2","remark-footnotes":"~2.0.0","shiki-twoslash":"^3.1.0","svelte":"^3.49.0","svelte-check":"^2.9.0","svelte-preprocess":"^4.10.7","tailwindcss":"^3.1.8","tslib":"^2.4.0","typescript":"^4.8.2","unist-util-visit":"^4.1.1","unocss":"^0.45.13","vite":"^3.1.0-beta.1","vite-plugin-pwa":"^0.12.4","workbox-window":"^6.5.4"})
Error during pnpm install
8:23:33 PM: Failing build: Failed to install dependencies

**Comment by Interstellar750** [comment]
Are you sure you are using the code of this project for deployment? According to the log you gave, this pnpm-lock file seems to come from [kwaa/blog](https://github.com/kwaa/blog/blob/main/pnpm-lock.yaml). 🤔

**Comment by favnfavnfavn** [comment]
i tried to fix problem with copying working urara website's pnpm-lock file but it doesnt work. Also i have tried to deploy urara again on another website and this problem occurs again.

**Comment by favnfavnfavn** [comment]
It looks like i did very bad things in my repo :D. So i opened new blog repo and it gives another error to me. (Something similar is given by my problemfully blog repo). Given error code is from my new repo. Also i use netlify for deploying if it is necessary.

8:03:15 PM: Installing @sveltejs/adapter-netlify...
8:03:16 PM: Failed during stage "building site": Build script returned non-zero exit code: 2
8:03:16 PM:  ERR_PNPM_UNEXPECTED_STORE  Unexpected store location
8:03:16 PM: The dependencies at "/opt/build/repo/node_modules" are currently linked from the store at "/opt/build/repo/node_modules/.pnpm-store/v3".
8:03:16 PM: pnpm now wants to use the store at "/opt/buildhome/.pnpm-store/v3" to link dependencies.
8:03:16 PM: If you want to use the new store location, reinstall your dependencies with "pnpm install".
8:03:16 PM: You may change the global store location by running "pnpm config set store-dir <dir> --global".
8:03:16 PM: (This error may happen if the node_modules was installed with a different major version of pnpm)
8:03:16 PM: error during build:
8:03:16 PM: Error: Could not install @sveltejs/adapter-netlify. Please install it yourself by adding it to your package.json"s devDependencies and try building your project again.
    at get_adapter (file:///opt/build/repo/node_modules/.pnpm/@sveltejs+adapter-auto@2.1.0_@sveltejs+kit@1.25.0/node_modules/@sveltejs/adapter-auto/index.js:87:11)
8:03:16 PM:     at async adapt (file:///opt/build/repo/node_modules/.pnpm/@sveltejs+adapter-auto@2.1.0_@sveltejs+kit@1.25.0/node_modules/@sveltejs/adapter-auto/index.js:112:19)
8:03:16 PM:     at async adapt (file:///opt/build/repo/node_modules/.pnpm/@sveltejs+kit@1.25.0_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/core/adapt/index.js:26:2)
8:03:16 PM:     at async finalise (file:///opt/build/repo/node_modules/.pnpm/@sveltejs+kit@1.25.0_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/exports/vite/index.js:814:7)
8:03:16 PM:     at async Object.handler (file:///opt/build/repo/node_modules/.pnpm/@sveltejs+kit@1.25.0_svelte@4.2.0_vite@4.4.9/node_modules/@sveltejs/kit/src/exports/vite/index.js:836:5)
8:03:16 PM:     at async PluginDriver.hookParallel (file:///opt/build/repo/node_modules/.pnpm/rollup@3.29.1/node_modules/rollup/dist/es/shared/node-entry.js:25461:17)
8:03:16 PM:     at async Object.close (file:///opt/build/repo/node_modules/.pnpm/rollup@3.29.1/node_modules/rollup/dist/es/shared/node-entry.js:26721:13)
8:03:16 PM:     at async build (file:///opt/build/repo/node_modules/.pnpm/vite@4.4.9_@types+node@20.6.0/node_modules/vite/dist/node/chunks/dep-df561101.js:48021:13)
8:03:16 PM:     at async CAC.<anonymous> (file:///opt/build/repo/node_modules/.pnpm/vite@4.4.9_@types+node@20.6.0/node_modules/vite/dist/node/cli.js:822:9)
8:03:16 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
8:03:16 PM: ERROR: "kit:build" exited with 1.
8:03:16 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
8:03:16 PM: ​
8:03:16 PM: "build.command" failed                                        
8:03:16 PM: ────────────────────────────────────────────────────────────────
8:03:16 PM: ​
8:03:16 PM:   Error message
8:03:16 PM:   Command failed with exit code 1: npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build (https://ntl.fyi/exit-code-1)
8:03:16 PM: ​
8:03:16 PM:   Error location
8:03:16 PM:   In build.command from netlify.toml:
8:03:16 PM:   npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build
8:03:16 PM: ​
8:03:16 PM:   Resolved config
8:03:16 PM:   build:
8:03:16 PM:     command: npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build
8:03:16 PM:     commandOrigin: config
8:03:16 PM:     environment:
8:03:16 PM:       - NPM_FLAGS
8:03:16 PM:       - AWS_LAMBDA_JS_RUNTIME
8:03:16 PM:     publish: /opt/build/repo/build
8:03:16 PM:     publishOrigin: config
8:03:16 PM:   functions:
8:03:16 PM:     "*":
8:03:16 PM:       node_bundler: esbuild
8:03:16 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
8:03:16 PM: Failing build: Failed to build site

**Comment by Interstellar750** [comment]
This bug should be caused by the removal of the `"@sveltejs/adapter-netlify": "^2.0.7"` package in [417b5d0](https://github.com/importantimport/urara/commit/417b5d0f7ddf641661b2cd730d4612c0e8809423). I looked at my Netlify build list and found this issue as well. I don’t know if the demo site is still built normally, but it can be repaired. You just need to reinstall it.

```bash
# install the latest `@sveltejs/adapter-netlify` dependency into package.json and pnpm-lock.yaml
pnpm add -D @sveltejs/adapter-netlify
```

Then submit the commit again and it should be work

**Comment by favnfavnfavn** [comment]
Sorry for disturbing again but i am not very good at this things. I am still learning. Where should i write this command piece?

**Comment by Interstellar750** [comment]
This command should be executed on your device terminal. Clone your Urara repository locally and cd to the directory before executing it. You can refer [Quick Start | Urara Docs](https://urara-docs.netlify.app/getting-started/quick-start.html) page

**Comment by favnfavnfavn** [comment]
Why this errors starting to occur nowadays? I tried to change blog photo and some config changes and it gives commit error. In past i dont have any errors for doing this things.


0s
Run pnpm install --frozen-lockfile
 ERR_PNPM_LOCKFILE_CONFIG_MISMATCH  Cannot proceed with the frozen installation. The current "overrides" configuration doesn't match the value found in the lockfile

Update your lockfile using "pnpm install --no-frozen-lockfile"
Error: Process completed with exit code 1.

**Comment by Interstellar750** [comment]
Which of the methods I mentioned above did you choose? I'm not quite sure what causes this problem.

But according to this log, it should still be caused by the mismatch between your package.json and pnpm-lock.yaml files.

If you want to modify dependencies, it is recommended to use the [pnpm command](https://pnpm.io/cli/add) instead of manually modifying it, because pnpm can automatically handle these two files for you.

**Comment by kwaa** [comment]
It looks like something went wrong with the template, I'll fix it afterward.

**Comment by kwaa** [comment]
Can you retry based on the latest commit (https://github.com/importantimport/urara/commit/97908c3336a48966af80410237501c90047f9c48)? If it's fixed, I'll close the issue.

**Comment by favnfavnfavn** [comment]
I've tried to deploy a new site from new repo from new template and firstly, it works very well but when i tried to add my old website's blog pages it gives me an error

2:40:52 PM: Node.js v21.6.1
2:40:52 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
2:40:52 PM: ERROR: "kit:build" exited with 1.
2:40:52 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
2:40:52 PM: ​
2:40:52 PM: "build.command" failed                                        
2:40:52 PM: ────────────────────────────────────────────────────────────────
2:40:52 PM: ​
2:40:52 PM:   Error message
2:40:52 PM:   Command failed with exit code 1: npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build (https://ntl.fyi/exit-code-1)
2:40:52 PM: ​
2:40:52 PM:   Error location
2:40:52 PM:   In build.command from netlify.toml:
2:40:52 PM:   npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build
2:40:52 PM: ​
2:40:52 PM:   Resolved config
2:40:52 PM:   build:
2:40:52 PM:     command: npx pnpm i --store=node_modules/.pnpm-store && npx pnpm build
2:40:52 PM:     commandOrigin: config
2:40:52 PM:     environment:
2:40:52 PM:       - NPM_FLAGS
2:40:52 PM:     publish: /opt/build/repo/build
2:40:52 PM:     publishOrigin: config
2:40:52 PM:   functions:
2:40:52 PM:     "*":
2:40:52 PM:       node_bundler: esbuild
2:40:53 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
2:40:53 PM: Failing build: Failed to build site

**Comment by kwaa** [comment]
> I've tried to deploy a new site from new repo from new template and firstly, it works very well but when i tried to add my old website's blog pages it gives me an error

Little information is available.  Maybe you can look for more detailed error reports?

**Comment by favnfavnfavn** [comment]
How can i do it in netlify

**Comment by kwaa** [comment]
> How can i do it on netlify

idk. maybe you could try to build it locally or provide a public [minimal replication](https://antfu.me/posts/why-reproductions-are-required#reproducible-projects-or-playgrounds) for debugging.

**Comment by favnfavnfavn** [comment]
Thanks very very much for your attention and time and sorry for my mistakes. It looks like i didnt change configs so this problem begins and sorry i dont see main error on top of error text i sent. My problems fixed after some changes.
